network: 'mainnet'
metaChainShardId: 4294967295
api:
  public: true
  private: false
cron:
  transactionProcessor: false
  transactionProcessorMaxLookBehind: 1000
  transactionCompleted: false
  transactionCompletedMaxLookBehind: 100
  transactionBatch: false
  transactionBatchMaxLookBehind: 100
  cacheWarmer: false
  fastWarm: false
  queueWorker: false
  elasticUpdater: false
  statusChecker: false
flags:
  useRequestCaching: false
  useKeepAliveAgent: false
  useTracing: false
  useRequestLogging: false
  useVmQueryTracing: false
  processNfts: false
  indexer-v3: false
  collectionPropertiesFromGateway: false
features:
  eventsNotifier:
    enabled: false
    port: 5674
    url: 'amqp://guest:guest@127.0.0.1:5672'
    exchange: 'all_events'
    queue: 'api-process-logs-and-events'
  guestCaching:
    enabled: false
    hitsThreshold: 100
    ttl: 12
  updateCollectionExtraDetails:
    enabled: false
  marketplace:
    enabled: false
    serviceUrl: 'https://nfts-graph.multiversx.com/graphql'
  exchange:
    enabled: false
    serviceUrl: 'https://graph.xexchange.com/graphql'
  dataApi:
    enabled: false
    serviceUrl: 'https://data-api.multiversx.com'
  auth:
    enabled: false
    maxExpirySeconds: 86400
    acceptedOrigins:
      - ''
    admins:
      - ''
    jwtSecret: ''
image:
  width: 600
  height: 600
  type: 'png'
aws:
  s3KeyId: ''
  s3Secret: ''
  s3Bucket: 'media.elrond.com'
  s3Region: ''
urls:
  self: 'https://api.multiversx.com'
  api:
    - 'https://api.multiversx.com'
    - 'https://devnet-api.multiversx.com'
    - 'https://testnet-api.multiversx.com'
  elastic:
    - 'https://index.multiversx.com'
  gateway:
    - 'https://xoxno-gateway-mainnet.whitemushroom-c526f76e.westeurope.azurecontainerapps.io'
  verifier: 'https://play-api.multiversx.com'
  redis: 'trustmarket.redis.cache.windows.net'
  rabbitmq: 'amqp://127.0.0.1:5672'
  providers: 'https://delegation-api.multiversx.com/providers'
  delegation: 'https://delegation-api.multiversx.com'
  media: 'https://media.elrond.com'
  nftThumbnails: 'https://media.elrond.com/nfts/thumbnail'
  tmp: '/tmp'
  ipfs: 'https://ipfs.io/ipfs'
  socket: 'socket-fra.elrond.com'
  maiarId: 'https://id-api.multiversx.com'
keyVault:
  url: https://trustmarketvault.vault.azure.net/
indexer:
  type: 'elastic'
  maxPagination: 10000
database:
  enabled: false
  url: 'mongodb://127.0.0.1:27017/api?authSource=admin'
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  database: 'api'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 50
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt'
  metabonding: 'erd1qqqqqqqqqqqqqpgq50dge6rrpcra4tp9hl57jl0893a4r2r72jpsk39rjj'
inflation:
  - 1952123
  - 1746637
  - 1541150
  - 1335663
  - 1130177
  - 924690
  - 719203
nftProcess:
  parallelism: 1
  maxRetries: 3